# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1300, 955)
        self.idx_data = QtWidgets.QLineEdit(Dialog)
        self.idx_data.setGeometry(QtCore.QRect(970, 40, 51, 25))
        self.idx_data.setText("")
        self.idx_data.setAlignment(QtCore.Qt.AlignCenter)
        self.idx_data.setObjectName("idx_data")
        self.dataInfo = QtWidgets.QLineEdit(Dialog)
        self.dataInfo.setGeometry(QtCore.QRect(20, 10, 1001, 25))
        self.dataInfo.setObjectName("dataInfo")
        self.idx = QtWidgets.QLineEdit(Dialog)
        self.idx.setGeometry(QtCore.QRect(890, 40, 71, 25))
        self.idx.setAlignment(QtCore.Qt.AlignCenter)
        self.idx.setObjectName("idx")
        self.map = QtWidgets.QLineEdit(Dialog)
        self.map.setGeometry(QtCore.QRect(20, 40, 101, 25))
        self.map.setAlignment(QtCore.Qt.AlignCenter)
        self.map.setObjectName("map")
        self.show_predict = QtWidgets.QCheckBox(Dialog)
        self.show_predict.setGeometry(QtCore.QRect(1040, 410, 136, 32))
        self.show_predict.setObjectName("show_predict")
        self.fde6_data = QtWidgets.QLineEdit(Dialog)
        self.fde6_data.setGeometry(QtCore.QRect(590, 40, 61, 25))
        self.fde6_data.setText("")
        self.fde6_data.setAlignment(QtCore.Qt.AlignCenter)
        self.fde6_data.setObjectName("fde6_data")
        self.ade6 = QtWidgets.QLineEdit(Dialog)
        self.ade6.setGeometry(QtCore.QRect(440, 40, 41, 25))
        self.ade6.setAlignment(QtCore.Qt.AlignCenter)
        self.ade6.setObjectName("ade6")
        self.fde1 = QtWidgets.QLineEdit(Dialog)
        self.fde1.setGeometry(QtCore.QRect(330, 40, 41, 25))
        self.fde1.setAlignment(QtCore.Qt.AlignCenter)
        self.fde1.setObjectName("fde1")
        self.ade6_data = QtWidgets.QLineEdit(Dialog)
        self.ade6_data.setGeometry(QtCore.QRect(480, 40, 61, 25))
        self.ade6_data.setText("")
        self.ade6_data.setAlignment(QtCore.Qt.AlignCenter)
        self.ade6_data.setObjectName("ade6_data")
        self.export_2 = QtWidgets.QPushButton(Dialog)
        self.export_2.setGeometry(QtCore.QRect(1040, 770, 141, 25))
        self.export_2.setObjectName("export_2")
        self.prev_idx = QtWidgets.QPushButton(Dialog)
        self.prev_idx.setGeometry(QtCore.QRect(1040, 40, 61, 25))
        self.prev_idx.setObjectName("prev_idx")
        self.loadData = QtWidgets.QPushButton(Dialog)
        self.loadData.setGeometry(QtCore.QRect(1040, 10, 141, 25))
        self.loadData.setObjectName("loadData")
        self.ade1_data = QtWidgets.QLineEdit(Dialog)
        self.ade1_data.setGeometry(QtCore.QRect(260, 40, 61, 25))
        self.ade1_data.setText("")
        self.ade1_data.setAlignment(QtCore.Qt.AlignCenter)
        self.ade1_data.setObjectName("ade1_data")
        self.ade1 = QtWidgets.QLineEdit(Dialog)
        self.ade1.setGeometry(QtCore.QRect(220, 40, 41, 25))
        self.ade1.setAlignment(QtCore.Qt.AlignCenter)
        self.ade1.setObjectName("ade1")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(1040, 80, 136, 321))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setHandleWidth(4)
        self.splitter.setObjectName("splitter")
        self.ego_path_enable = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_enable.setObjectName("ego_path_enable")
        self.ego_path_aug_1 = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_aug_1.setObjectName("ego_path_aug_1")
        self.ego_path_aug_2 = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_aug_2.setObjectName("ego_path_aug_2")
        self.ego_path_aug_3 = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_aug_3.setObjectName("ego_path_aug_3")
        self.ego_path_aug_4 = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_aug_4.setObjectName("ego_path_aug_4")
        self.ego_path_aug_5 = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_aug_5.setObjectName("ego_path_aug_5")
        self.ego_path_aug_6 = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_aug_6.setObjectName("ego_path_aug_6")
        self.ego_path_aug_7 = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_aug_7.setObjectName("ego_path_aug_7")
        self.ego_path_aug_8 = QtWidgets.QCheckBox(self.splitter)
        self.ego_path_aug_8.setObjectName("ego_path_aug_8")
        self.data_num = QtWidgets.QLineEdit(Dialog)
        self.data_num.setGeometry(QtCore.QRect(120, 40, 91, 25))
        self.data_num.setText("")
        self.data_num.setAlignment(QtCore.Qt.AlignCenter)
        self.data_num.setObjectName("data_num")
        self.fde6 = QtWidgets.QLineEdit(Dialog)
        self.fde6.setGeometry(QtCore.QRect(550, 40, 41, 25))
        self.fde6.setAlignment(QtCore.Qt.AlignCenter)
        self.fde6.setObjectName("fde6")
        self.next_idx = QtWidgets.QPushButton(Dialog)
        self.next_idx.setGeometry(QtCore.QRect(1120, 40, 61, 25))
        self.next_idx.setObjectName("next_idx")
        self.pred_plot = matplotlibWidget(Dialog)
        self.pred_plot.setGeometry(QtCore.QRect(20, 80, 1001, 721))
        self.pred_plot.setObjectName("pred_plot")
        self.fde1_data = QtWidgets.QLineEdit(Dialog)
        self.fde1_data.setGeometry(QtCore.QRect(370, 40, 61, 25))
        self.fde1_data.setText("")
        self.fde1_data.setAlignment(QtCore.Qt.AlignCenter)
        self.fde1_data.setObjectName("fde1_data")
        self.fov_data = QtWidgets.QLineEdit(Dialog)
        self.fov_data.setGeometry(QtCore.QRect(1090, 740, 91, 25))
        self.fov_data.setText("")
        self.fov_data.setAlignment(QtCore.Qt.AlignCenter)
        self.fov_data.setObjectName("fov_data")
        self.fov_5 = QtWidgets.QLineEdit(Dialog)
        self.fov_5.setGeometry(QtCore.QRect(1040, 680, 51, 25))
        self.fov_5.setAlignment(QtCore.Qt.AlignCenter)
        self.fov_5.setObjectName("fov_5")
        self.fov_1 = QtWidgets.QLineEdit(Dialog)
        self.fov_1.setGeometry(QtCore.QRect(1040, 740, 51, 25))
        self.fov_1.setAlignment(QtCore.Qt.AlignCenter)
        self.fov_1.setObjectName("fov_1")
        self.y_offset_data = QtWidgets.QLineEdit(Dialog)
        self.y_offset_data.setGeometry(QtCore.QRect(1090, 710, 91, 25))
        self.y_offset_data.setText("")
        self.y_offset_data.setAlignment(QtCore.Qt.AlignCenter)
        self.y_offset_data.setObjectName("y_offset_data")
        self.x_offset_data = QtWidgets.QLineEdit(Dialog)
        self.x_offset_data.setGeometry(QtCore.QRect(1090, 680, 91, 25))
        self.x_offset_data.setText("")
        self.x_offset_data.setAlignment(QtCore.Qt.AlignCenter)
        self.x_offset_data.setObjectName("x_offset_data")
        self.fov_6 = QtWidgets.QLineEdit(Dialog)
        self.fov_6.setGeometry(QtCore.QRect(1040, 710, 51, 25))
        self.fov_6.setAlignment(QtCore.Qt.AlignCenter)
        self.fov_6.setObjectName("fov_6")
        self.data_dir = QtWidgets.QLineEdit(Dialog)
        self.data_dir.setGeometry(QtCore.QRect(660, 40, 61, 25))
        self.data_dir.setAlignment(QtCore.Qt.AlignCenter)
        self.data_dir.setObjectName("data_dir")
        self.data_dir_data = QtWidgets.QLineEdit(Dialog)
        self.data_dir_data.setGeometry(QtCore.QRect(720, 40, 161, 25))
        self.data_dir_data.setText("")
        self.data_dir_data.setAlignment(QtCore.Qt.AlignCenter)
        self.data_dir_data.setObjectName("data_dir_data")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.idx.setText(_translate("Dialog", "row idx"))
        self.map.setText(_translate("Dialog", "Num of data"))
        self.show_predict.setText(_translate("Dialog", "plot prediction"))
        self.ade6.setText(_translate("Dialog", "ade6"))
        self.fde1.setText(_translate("Dialog", "fde1"))
        self.export_2.setText(_translate("Dialog", "export"))
        self.prev_idx.setText(_translate("Dialog", "prev"))
        self.loadData.setText(_translate("Dialog", "Load Data Folder"))
        self.ade1.setText(_translate("Dialog", "ade1"))
        self.ego_path_enable.setText(_translate("Dialog", "ego path in data"))
        self.ego_path_aug_1.setText(_translate("Dialog", "ego path cand 1"))
        self.ego_path_aug_2.setText(_translate("Dialog", "ego path cand 2"))
        self.ego_path_aug_3.setText(_translate("Dialog", "ego path cand 3"))
        self.ego_path_aug_4.setText(_translate("Dialog", "ego path cand 4"))
        self.ego_path_aug_5.setText(_translate("Dialog", "ego path cand 5"))
        self.ego_path_aug_6.setText(_translate("Dialog", "ego path cand 6"))
        self.ego_path_aug_7.setText(_translate("Dialog", "ego path cand 7"))
        self.ego_path_aug_8.setText(_translate("Dialog", "ego path cand 8"))
        self.fde6.setText(_translate("Dialog", "fde6"))
        self.next_idx.setText(_translate("Dialog", "next"))
        self.fov_5.setText(_translate("Dialog", "x"))
        self.fov_1.setText(_translate("Dialog", "FOV"))
        self.fov_6.setText(_translate("Dialog", "y"))
        self.data_dir.setText(_translate("Dialog", "data dir"))

from matplotlibwidgetFile import matplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

